version: "3.8"

services:
  websocket-server:
    build: .
    scale: 20
    networks:
      - app-network
    expose:
      - "12333"
    ports:
      - "12333:12333"
    environment:
      - WEBSOCKET_SERVER=true

  redis:
    image: "redis:alpine"
    networks:
      - app-network
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "API-DB"
    networks:
      - app-network

  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Expose Nginx on port 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
